codedaddies_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
]

my_app/urls.py
from django.urls import path
from . import views

app_name = 'my_app'
urlpatterns = [
    path('', views.home, name='home_page'),
    path('new_search', views.new_search, name='new_search')
]

my_app/models.py
from django.db import models

# Create your models here.
class Search(models.Model):
    search = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}'.format(self.search)

    class Meta:
        verbose_name_plural = "Searches"

my_app/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
import requests
from requests.compat import quote_plus, quote
from . import models
import re

# BASE_CRAIGSLIST_URL = "https://colombia.craigslist.org/search/jjj?query={}"
BASE_CRAIGSLIST_URL = "https://listado.mercadolibre.com.co/{}"

# Create your views here.
def home(request):
    return render(request, template_name='base.html')

def new_search(request):
    
    search = request.POST.get('search')
    models.Search.objects.create(search=search)
    final_url = BASE_CRAIGSLIST_URL.format(quote(search))
    response = requests.get(final_url)
    data = response.text
    soup = BeautifulSoup(markup=data, features='html.parser')

    post_listings = []
    post_listings = soup.find_all(name='li', class_= re.compile('results-item highlighted article'))
    # post_location = post_listings[0].find(class_='item__location').text

    final_postings = []
    for post in post_listings:
        post_title = post.find(class_='main-title').text
        if post.find(class_='item__price'):
            post_price = post.find(class_='item__price').text
        else:
            post_price = 'N/A'
        post_url = post.find('a').attrs['href']
        post_img = post.find_all(name='img')
        # print("\n-------------------------------------------------\n", post)

        # post_img = post_img[0].get("src")
        if post_img[0].get("src") is None:
            post_img = post_img[0].get("data-src")
        else:
            post_img = post_img[0].get("src")
        # print("---------------------------\nIMAGE: ", post_img)

        final_postings.append({'url': post_url, 'title': post_title, 'price': post_price, 'img': post_img})
    
    stuff_for_frotend = {'search':search, 'final_postings': final_postings}
    
    return render(request, template_name='my_app/new_search.html', context=stuff_for_frotend)
    

templates/base.html
{% load staticfiles %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Codedaddies List</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% comment %} <script src="https://kit.fontawesome.com/a076d05399.js"></script> {% endcomment %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body>
<nav>
    <div class="container nav-wrapper">
        <a href="{% url 'my_app:home_page' %}" class="brand-logo">Codedaddies List</a>
        <ul id="nav-mobile" class="right">
            <li><a href="{% url 'my_app:home_page' %}">Home</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    <h1 style="text-align: center">What do you want to search for on Codedaddies List?</h1>
    <div class="row">
        <div class="col s4">
            <!-- Promo Content 1 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: #EE6E73">directions_run</i>
                <p>Fast craigslist web scraper</p>
                <p class="light center">Scrape away right here with a beautiful GUI.</p>
            </div>
        </div>

        <div class="col s4">
            <!-- Promo Content 2 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: orange">search</i>
                <p>Filter your searches</p>
                <p class="light center">We built in functionality to filter based on pricing.</p>
            </div>
        </div>

        <div class="col s4">
            <!-- Promo Content 3 goes here -->
            <div class="center">
                <i class="large material-icons" style="color: blue">chrome_reader_mode</i>
                <p>A much sexier front-end to Craigslist</p>
                <p class="light center">We built this with ❤️</p>
            </div>
        </div>
    
    <form action="{% url 'my_app:new_search' %}" method="post">
        {% csrf_token %}
        <input type="text" name="search" placeholder="Search">
        <button class="btn waves-effect waves-light btn-daniel" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>

    {% block content %}

    {% endblock content %}

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/my_app/new_search.html
{% extends 'base.html' %}

{% block content %}
    <h2 style="text-align: center">{{search | title}} </h2>
    <div class="row">
    {% for post in final_postings %}
        <div class="col s4">
            <div class="card">
                <div class="card-image">
                    <a href="{{ post.url }}"><img src="{{ post.img }}" alt=""></a>
                </div>
                <div class="card-content">
                    <p>{{ post.title }}</p>
                </div>
                <div class="card-action">
                    <a href="{{ post.url }}">View listing: Price {{ post.price }} COP </a>
                </div>
            </div>
        </div>
    
    {% comment %} MINUTO 6:23:51 {% endcomment %}    
    {% endfor %}
    </div>
{% endblock content %}